### ISSUE TITLE
What is the exact feature set of this project?

### ISSUE THREAD

**Issue by themg95** [cgytrus/SixDash#1]
In the readme you said: _Other utilities useful for 3Dash mod developers._ As a 3Dash mod developer, what are these features?

**Comment by cgytrus** [comment]
there's no documentation yet, so atm you can really only see it in code in the SixDash.API namespace

**Comment by cgytrus** [comment]
update: there's now xml documentation
i will close this issue once i setup automatic docs generation from xml docs with smth like docfx or doxygen

**Comment by cgytrus** [comment]
done :p
https://6dash.cgyt.ru/
